### PR TITLE
added support for BitBucket accounts

### PR DESCRIPTION
**Pull request by ZielinskiLukasz**

### CODE REVIEW

**Comment by darwiin** [comment]
Hi,
Thanks for your contribution. Why did you remove the medium macros ?

**Comment by ZielinskiLukasz** [comment]
It wasn't intentional, I think I checked out some older version of the repo without medium macro. Sorry about that

**Comment by darwiin** [comment]
Thanks for your response. No worries. I will merge your PR soon.

**Comment by ZielinskiLukasz** [comment]
I restored medium command, please try again, thank  you

**Comment by darwiin** [comment]
Thanks

**Pull request merged**
